mozilla/bleach

- bleach/__init__.py
- bleach/tests/test_basics.py
- docs/clean.rst
For one of my projects, I required configurable protocols for the href attribute of anchor tags when using bleach.clean. This pull request exposes the allowed protocols in bleach.clean.
> Made protocols configurable.

- bleach/__init__.py
- tests/test_links.py
This fixes PR #207 which broke when I converted to py.test.
> Use ASCII digits in port number parsing

- .travis.yml
It's failing now with Python 2.6 because flake8 doesn't work with Python
2.6. It's failing with Python 3.2 because py.test doesn't work with
Python 3.2.
I'm not quite ready to drop support for both of them, though. So for
now, let's allow the failures.
> Allow travis to fail with Python 2.6 and 3.2

- tests/test_basics.py
linkify can return text with html attributes in a different order
depending on how the attributes come out of the attrs dict. Because of
that, there are several possible outcomes.
This fixes the linkify test to accept both of them.
Fixes #161
> Fix test_idempotent to not sometimes fail

- CHANGES
- bleach/__init__.py
- tests/test_links.py
When linkify is removing nodes, it wasn't capturing the node tail text.
Thus it'd lose text it shouldn't have been losing.
Fixes #132
> Fix linkify with node tails

- bleach/sanitizer.py
This redoes the innards of allow_token so that it's a single loop across all the
attributes in a token rather than a bunch of little passes.
This has less looping, so theoretically it's more optimal, but I didn't spend
any time testing that theory.
> Refactor allow_token

- bleach/__init__.py
- bleach/sanitizer.py
- docs/clean.rst
- tests/test_basics.py
This lets users extend cleaning more easily by specifying an html5lib Filter.
Fixes #58.
> Implement ability to use Filters in cleaning

- CHANGES
- bleach/__init__.py
- bleach/linkifier.py
- bleach/sanitizer.py
- docs/clean.rst
- docs/linkify.rst
- tests/test_basics.py
- tests/test_links.py
This is a ton of changes all in one commit. Sorry.
* Restructures linkify so it mirrors clean. This has the nicety in that
the two are parallel and can be used the same.
* Rework how url_re and email_re work so that it's possible to override
them and/or provide your own list of allowed procotols and TLDs
* Overhaul the docs including converting linkify examples to doctest
* Update CHANGES
> Restructure linkify; clean up __init__; update docs

- CHANGES
- bleach/sanitizer.py
- docs/clean.rst
- tests/test_basics.py
- tests/test_security.py
This reworks how attributes argument works. Callables now take three arguments:
tag, attribute name and attribute value. Callables can be passed in as the
attributes argument value or as a value for any of the tags in the dict.
This also reworks the implementation so the complexity of the different shapes
is shuffled away out of ``allow_token`` which simplifies it a bit.
Fixes #126.
> Rework attributes value and filters

- CHANGES
- README.rst
- bleach/__init__.py
- bleach/linkifier.py
- bleach/sanitizer.py
- docs/goals.rst
- docs/linkify.rst
- setup.py
- tests/test_links.py
This changes skip_pre to a more general skip_tags that lets you skip linkifying
in a specified list of tags--not just pre.
This fixes #194.
> Change skip_pre to the more general skip_tags

- README.rst
- docs/goals.rst
Used notes provided by @willkg on #277 to add a short description of why Bleach may be preferable to html5lib’s built-in sanitizer.
Let me know if you think this should live somewhere else.
> Add comparison of Bleach vs html5lib to README

- setup.py
- tox.ini
Mark package compatible with html5lib versions >=1.0b9.
> Fix html5lib requirements

- docs/clean.rst
- docs/dev.rst
- docs/goals.rst
This clarifies the dangers usage of `bleach.clean` output in HTML attributes with examples and some other commentary.
> Clarify the dangers of using bleach.clean() output in html attributes

- bleach/linkifier.py
- bleach/sanitizer.py
- tests/test_links.py
- tests/test_security.py
Linkify and clean should accept only six.string_types and otherwise now they raise TypeError.
This PR solves the issue: #292
> Linkify and clean should accept only six.string_types

- .gitignore
- bleach/linkifier.py
- setup.py
- tests/test_links.py
Do not create a http link inside a mailto link
Partly fixes #300:
```py
>>> linkify('foo@exa-mple.com', parse_email=True)
'<a href="mailto:foo@exa-mple.com">foo@exa<a href="http://-mple.com" rel="nofollow">-mple.com</a></a>'
'<a href="mailto:foo@exa-mple.com">foo@exa-mple.com</a>'
```
but it does not fix this issue:
```py
>>> linkify('foo@bar-baz.com')
'foo@bar<a href="http://-baz.com" rel="nofollow">-baz.com</a>'
```
> Fix links in mails with hyphen

- docs/clean.rst
- docs/goals.rst
This makes it more explicit and hopefully clarifies for people who might not understand "HTML" vs. "HTML attribute".
> Further clarify where it's safe to use bleach.clean() output

- bleach/sanitizer.py
- tests/test_clean.py
so, for example, the error message will be 'argument cannot be of int type, must be of text type'.
It can help for debugging.
> Insert the provided type in error message when it's a wrong one

- MANIFEST.in
- tests_website/data_to_json.py
I squashed test cases into single files--no more `.out` files. This carries
that change through to `MANIFEST.in` and our tests_website system.
I missed this in the previous cleanup passes. :(
> Fix MANIFEST and data_to_json.py related to recent changes

- bleach/sanitizer.py
- tests/test_clean.py
This fixes an issue in uri sanitizing where character entities in the schema muck up the matching which allows disallowed schemes through.
> Fix url sanitizing

- bleach/sanitizer.py
- tests/data/6.test
- tests/test_clean.py
This fixes the ambiguous ampersand case in character entity handling in
attribute values.
Fixes #359
> Handle ambiguous ampersands correctly

- bleach/sanitizer.py
- tests/test_clean.py
Issue 352 has a string that manages to tokenize an html attribute with
a namespace, but no name. Then the namespace doesn't exist in prefixes
and that throws a `KeyError`.
This alleviates that a bit such that if there's a namespace, but no
name, it swaps the two values. Further, if prefixes doesn't have the
namespace, then it ignores the namespace.
Fixes #352
> Handle nonexistent namespaces better

- bleach/sanitizer.py
- tests/test_css.py
The CSS is in an HTML attribute value, so we need to convert character
entities in it which makes it proper CSS before we can sanitize it.
Fixes #363
> Convert entities in CSS values before sanitizing

- README.rst
This isn't earth-shattering or anything. I haven't tested `easy_install` installation ever, so I don't even know if it works anymore.
Fixes #373.
> Drop easy_install instructions

- CHANGES
- bleach/__init__.py
- bleach/html5lib_shim.py
- bleach/linkifier.py
- bleach/sanitizer.py
- tests/test_clean.py
- tests/test_html5lib_shim.py
This creates an intermediary `html5lib_shim` module between the html5lib
library and Bleach. This will make it easier to update html5lib and fix
any issues that arise from that.
We're going to treat this as an incompatible API change, so changing
the upcoming version to 3.0.0.
Fixes #316
> Extract all html5lib things into a shim module

- bleach/html5lib_shim.py
- bleach/linkifier.py
- bleach/sanitizer.py
- docs/linkify.rst
- tests/test_html5lib_shim.py
- tests/test_linkify.py
This tweaks the code for the `BleachHTMLParser` and `BleachHTMLTokenizer` to work with the needs of the linkifier. This fixes the case where the linkifier was "fixing" non-HTML tags like `</sarcasm>`.
Fixes #392.
> fixes #392: linkify fix

- bleach/html5lib_shim.py
This undoes something I did for better readability. If the token is a tag,
then it doesn't have a string value for data. This fixes the handling.
Fixes #398.
> Fix token['data'] usage in error handling

- bleach/html5lib_shim.py
- scripts/vendor_verify.sh
This fixes the issue where linkify will escape `<abbr>`.
Fixes #400
> Add abbr to HTML_TAGS

- .travis.yml
- CHANGES
- scripts/vendor_verify.sh
- setup.py
- tox.ini
This fixes `vendor_verify.sh` script accounting for `RECORD` being unsorted and occasionally failing the diff.
This also adds testing Bleach in Python 3.7 to tox and Travis.
> fix 377 - add python 3.7 support

- docs/dev.rst
We stopped doing releases through Travis CI. This updates the release process docs to reflect that.
> Update release process

- bleach/linkifier.py
- bleach/sanitizer.py
- tests/test_clean.py
- tests/test_linkify.py
The sanitizer causes fracturing of `Characters` tokens. That causes problems
with anything downstream in the filters because now the things they're
looking for can be split across token boundaries.
Instead of dealing with that, this fixes the sanitizer to merge characters
tokens as they're being yielded.
Fixes #374
> Merge Characters tokens

- bleach/sanitizer.py
This fixes regex strings. They should always be marked raw since they have `\` in them and that needs to get interpreted as a regex `\` and not a Python string `\`.
> Fix regex strings--they should be marked raw

- setup.py
After tracing through a build failure in our of my projects, I found out that (1) we weren't clearing our virtualenv's in our builds and (2) your vendored version of [html5lib requires `six>=1.9`](https://github.com/html5lib/html5lib-python/blob/1.0.1/requirements.txt#L1).  It's buried in the [vendored METADATA](https://github.com/mozilla/bleach/blob/master/bleach/_vendor/html5lib-1.0.1.dist-info/METADATA#L25) file as well.
For the sake of posterity and googler's everywhere, here's the traceback that I got with an older version of six installed.
```
Traceback (most recent call last):
File "./setup.py", line 47, in <module>
'Programming Language :: Python :: 2.7',
File "/var/lib/jenkins/shiningpanda/jobs/1f336430/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/setuptools/__init__.py" …
```
> Fix six dependency in setup.py

- bleach/linkifier.py
- docs/linkify.rst
- tests/test_linkify.py
`recognized_tags` lets someone specify a different set of recognized tags
to the `Linker` when they're using it by itself. One use of this is if
you're doing a clean pass, storing that, and then linkifying on demand.
The `recognized_tags` argument lets you re-use the allowed tags from the
clean step and then there isn't any additional oddities occuring in
the linkify step.
Fixes #409
> Add recognized_tags to Linker arguments

- bleach/sanitizer.py
- tests/test_linkify.py
This fixes a problem in `LinkifyFilter` when using it with the `Cleaner` where
the `Cleaner` sets up the tokenizer to not consume entities. So character
entities end up in their own `Entity` tokens and `Linkifyfilter` can't match
links that cross token boundaries. If there's a `&amp;`, then `LinkifyFilter`
won't match across that.
This fixes that by converting `&amp;` to `&` in the sanitizer when it's pulling out
entities and putting them in separate `Entity` tokens. The `&` `Characters` tokens
will get merged by `BleachSanitizerFilter.__iter__` and `&` will get converted
back to `&amp;` in the serialier.
Fixes #422
> Convert &amp; to & as a Characters token

- CHANGES
- bleach/__init__.py
- bleach/html5lib_shim.py
- tests/test_html5lib_shim.py
- tests/test_linkify.py
When parsing a <meta encoding=""> tag, the parser calls charEncoding
and changeEncoding in the input stream, but the InputStreamWithMemory
wrapper didn't have those methods. This fixes that.
This also creates a new test set for BleachHTMLParser functionality.
Fixes #431
> Fix parsing "meta" tag with encoding attribute

- bleach/callbacks.py
- bleach/html5lib_shim.py
- bleach/linkifier.py
- bleach/sanitizer.py
- tests/test_callbacks.py
- tests/test_clean.py
- tests/test_css.py
- tests/test_html5lib_shim.py
- tests/test_linkify.py
Using `from __future__ import unicode_literals` guarantees that all string literals will be Unicode strings by default. Using the u prefix is redundant. Cleans up the code towards a Python 3 style.
> Remove u string prefix in files with unicode_literals

- .travis.yml
- tox.ini
In Travis, use `dist: xenial` by default to provide support for all test platforms.
> Add pypy3 testing to tox and Travis

- tests/test_clean.py
Always close the open file by using a context manager. Previously
Appeared as:
tests/test_clean.py:790
tests/test_clean.py:790: ResourceWarning: unclosed file <_io.TextIOWrapper name='.../tests/data/1.test' mode='r' encoding='UTF-8'>
for fn in tests
> Fix ResourceWarning emitted during tests

- setup.py
Use io over codecs. It is the more recently developed library and
follows the same semantics as Python3's builtin open.
Warnings appeared as:
setup.py:37: ResourceWarning: unclosed file <_io.BufferedReader name='bleach/__init__.py'>
version_file = codecs.open(fn, mode='r', encoding='utf-8').read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
setup.py:28: ResourceWarning: unclosed file <_io.BufferedReader name='README.rst'>
desc = codecs.open('README.rst', encoding='utf-8').read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
setup.py:30: ResourceWarning: unclosed file <_io.BufferedReader name='CHANGES'>
desc += codecs.open('CHANGES', encoding='utf-8').read()
> Fix ResourceWarnings emitted from setup.py

- README.rst
Rebased #449 so we can land it by the 30th.
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
> Update PyPI link to new location

- bleach/linkifier.py
Whilst working on the [Reproducible Builds effort](https://reproducible-builds.org/) I noticed that python-bleach could not be built reproducibly.
This is because the documentation included a default arguments that was (originally) generated from a `frozenset` type which are iterated over at runtime in a nondeterministic order.
This commit therefore ensures a regular expression is constructed in a deterministic manner, rendering the documentation reproducible.
This bug was originally filed in Debian as [#934120](https://bugs.debian.org/934120).
> Make the documentation reproducible

- bleach/html5lib_shim.py
- bleach/linkifier.py
- bleach/sanitizer.py
Carries #466 without merging master back into the feature branch. Previously reviewed in that PR.
> Typo fixes

- docs/clean.rst
- docs/goals.rst
Carries #454 without merging master back into the feature branch. Previously reviewed in that PR.
> Correct typo: bleach.clean(user_bio} → bleach.clean(user_bio)

- requirements-dev.txt
force pytest <5 to workaround #459 #467 and I'll make a new issue for supporting / upgrading to pytest 5+ (edit: done in #475)
r? @jdufresne
> require pytest 5+ and update exception handling tests

- docs/linkify.rst
fixes: #472 see the linked issues for additional info.
Surfaces the `build_url_re` docstring and adds a couple examples to the docs. One possible downside is if we move away from the `url_re` kwarg then it'll break backwards compatibility, but I think that's OK.
r? @jdufresne or @willkg
> docs: Add linkify Linker examples using custom TLDs and protocols

- .travis.yml
- scripts/run_tests.sh
- tox.ini
This fixes `tox.ini` to run doctests with the `docs` environment. You can run it manually like this:
```
$ tox -e docs
```
I also tweaked the CI setup to build the docs and run doctests in CI. I think that'll work.
> Fix tox.ini to run doctests in docs

- README.rst
- docs/dev.rst
Mozilla is shutting down irc.mozilla.org soon. We should stop talking about the IRC channel.
Fixes #482
> Remove references to IRC

- .gitignore
- requirements-dev.txt
- tests/test_clean.py
per @mastizada in #483
> Tox test with python 2.7 and 3.7 passed (python 3.7 gave warning for html5lib - external library).
> Don't know what was the issue with python 2.7 before, but just making these 2 changes worked in both. I was going to add a solution for python 2 case, but it wasn't needed.
> 
> Fixes #459
> Fixes #475
Fixes #459
Fixes #475
> Support pytest5 syntax for tests

- README.rst
The ending quote for a string in code example is missing. This PR adds it.
> Add missing quote

- setup.cfg
- setup.py
Since setuptools v41.5.0 (27 Oct 2019), the 'test' command is formally
deprecated and should not be used. Contributors should run test tests
using tox, pytest, run_test.sh or some other entry point.
For details on the setuptools change, see:
https://setuptools.readthedocs.io/en/latest/history.html#v41-5-0
> Drop deprecated 'setup.py test' support

- .travis.yml
Plain `pypy` and `pypy3` now point to PyPy 7.1.1.
> Travis CI: test on PyPy 7

- .travis.yml
- setup.py
- tox.ini
Python 3.4 is EOL and no longer receiving security updates (or any updates) from the core Python team.
Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.4 | 2014-03-16 | 2019-03-16
Source: https://en.wikipedia.org/wiki/CPython#Version_history
It's also little used. Here's the pip installs for bleach from PyPI for December 2019:
| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  45.22% | 2,184,849 |
| 3.6      |  24.90% | 1,203,109 |
| 3.7      |  17.44% |   842,550 |
| 3.5      |   9.00% |   434,677 |
| 3.8      |   2.53% |   122,121 |
| 3.4      |   0.65% |    31,312 |
| null     |   0.26% |    12,381 |
| 3.9      |   0.01% |       342 |
| 3.3      |   0.00% |        20 |
| 2.6      |   0.00% | …
> Drop support for EOL Python 3.4

- CHANGES
- CONTRIBUTORS
- bleach/__init__.py
Currently, we're maintaining as separate v3.1 branch confusingly called [v3.1.0-branch](https://github.com/mozilla/bleach/tree/v3.1.0-branch) for security releases. 
This PR gets the two branches in sync for a 3.1.3 release and to cut future releases from master.
I'm open to alternate branching and development schemes too.
> Update for v3.1.3 release

- bleach/__init__.py
- setup.py
bleach had a (undeclared) dependency on setuptools via the import of pkg_resources in __init__.py. pkg_resources is mostly deprecated, and its use should be avoided. For bleach's usage, we can directly employ the packaging library.
> Replace setuptools dependency with packaging.

- CHANGES
- SECURITY.md
- bleach/__init__.py
https://github.com/mozilla/bleach/blob/master/docs/dev.rst
no changes to manifest.in
> Update for v3.2.0 release

- .travis.yml
- bleach/__init__.py
- bleach/callbacks.py
- bleach/html5lib_shim.py
- bleach/linkifier.py
- bleach/sanitizer.py
- bleach/utils.py
- scripts/run_tests.sh
- setup.cfg
- tests/test_callbacks.py
- tests/test_clean.py
- tests/test_css.py
- tests/test_html5lib_shim.py
- tests/test_linkify.py
- tests/test_unicode.py
- tests/test_utils.py
- tests_website/data_to_json.py
- tests_website/open_test_page.py
- tests_website/server.py
- tox.ini
* Apply the black formatter to bleach tests and unvendored code
* Add a `format-check` target to `scripts/run-tests.sh`
* Add tox and CI jobs that fail if new code isn't formatting 
Note: that we don't add `black` to `requirements-dev.txt`, because it's Py3 only (refs: #520)
> paint it black

- CHANGES
- bleach/__init__.py
- bleach/html5lib_shim.py
- tests/test_html5lib_shim.py
- tests_website/index.html
Fix `convert_entity` exceptions for certain inputs
r? @willkg
> Validate convert entity code points

- tests/test_clean.py
Add tests for other tags that disallow child elements in the html namespace reported by Michał Bentkowski at Securitum and reflected in the updated https://github.com/mozilla/bleach/security/advisories/GHSA-vv2x-vrpj-qqpq advisory
Note: the sanitize code is unchanged. These tests are added for completeness to catch future regressions.
> tests: add tests for more eject tags for GHSA-vv2x-vrpj-qqpq

- CHANGES
I noticed this while browsing [the docs](https://bleach.readthedocs.io).
> Remove duplicated h1 in changelog

- docs/dev.rst
- scripts/vendor_verify.sh
- tox.ini
fix #598 
Changes:
* fix vendor verification script to fail when extra files are included
* update release process docs
* bump python versions in tox for vendorverify and lint tasks
Functional Test:
```
diffing directory trees...
Only in bleach/_vendor/: extra-file
```
```
/tmp/vendor-test exists. Please remove.
```
> Fix 598 verify vendor

- docs/linkify.rst
Think this should be 'title' instead of 'rel' if it refers to the example above?
> Fix attribute name in linkify docs.

- docs/clean.rst
- docs/linkify.rst
fix #594 
no warnings in https://github.com/mozilla/bleach/pull/609/checks?check_run_id=3265561864
> Fix 594 docbuild warnings

- .github/workflows/test.yml
- setup.py
- tox.ini
Python 3.10.0 RC2 was released [yesterday](https://discuss.python.org/t/python-3-10-0rc2-is-now-available/10496?u=hugovk), 3.10.0 final is due out [2021-10-04](https://www.python.org/dev/peps/pep-0619/).
> Add support for Python 3.10

- .github/workflows/test.yml
follow up to #614
~~Blocked on support in https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json (latest is 3.10.0-rc.2).~~
> ci: drop -dev from 3.10 test matrix

- CODE_OF_CONDUCT.rst
- docs/dev.rst
This removes the duplicate reST version of the CODE_OF_CONDUCT.md file.
Fixes #619.
> Remove CODE_OF_CONDUCT.rst (#619)

- .github/workflows/test.yml
- bleach/__init__.py
- bleach/html5lib_shim.py
- bleach/linkifier.py
- bleach/sanitizer.py
- docs/conf.py
- scripts/run_tests.sh
- setup.cfg
- setup.py
- tests/test_linkify.py
- tests/test_unicode.py
- tests_website/data_to_json.py
- tests_website/open_test_page.py
- tests_website/server.py
- tox.ini
Python 3.6 is EOL and no longer receiving security updates (or any updates) from the core Python team.
| cycle | latest |  release   |    eol     |
|:------|:-------|:----------:|:----------:|
| 3.10  | 3.10.1 | 2021-10-04 | 2026-10-04 |
| 3.9   | 3.9.9  | 2020-10-05 | 2025-10-05 |
| 3.8   | 3.8.12 | 2019-10-14 | 2024-10-14 |
| 3.7   | 3.7.12 | 2018-06-27 | 2023-06-27 |
| 3.6   | 3.6.15 | 2016-12-23 | 2021-12-23 |
https://endoflife.date/python
> Drop support for EOL Python 3.6

- tests/test_clean.py
- tests/test_linkify.py
This breaks up the existing idempotent tests into ones that are more specific rather than one big smorgasbord.
This adds test cases covering querystring parameters.
This supersedes #632.
> Add more idempotent tests

- docs/goals.rst
fix: #627
This one took me longer to get too than anticipated. 
This PR does not claim support for any browsers in favor of waiting until we can test output in them E2E #242
> docs: add CSS-based XSS and privacy leak prevention to non-goals

- bleach/html5lib_shim.py
- tests/test_clean.py
This fixes a bug where things in the form of a character entity (starts with &, some letters, and ends with ;) that aren't character entities get mangled. Now they are correctly handled.
This also fixes a bug where things in the form of a character entity that aren't character entities should have had the & escaped, but that wasn't happening.
After this, Bleach does the following:
* valid character entities that start with a & and end with a ; are left alone
* things that start with a & and end with a ; and aren't valid character entities are treated as text and the & is escaped
* things that start with a & but don't end with a ; are treated as text and the & is escaped
This is easy to reason about and idempotent and doesn't suffer from ambiguous edge cases where Bleach can't know what …
> Fix character entity handling (#450)

- bleach/linkifier.py
- tests/test_linkify.py
> Correctly urlencode email address parts

- docs/Makefile
Sphinx changed the format of the Makefile that's generated when you do
quickstart. This updates our docs Makefile accordingly.
> Update docs Makefile to new format

- bleach/html5lib_shim.py
- tests/test_clean.py
The html5lib tokenizer kicks up a parse error token when there's a `<`
that isn't the start of a tag. This adds some handling for that case and
treats the `<` plus whatever is after it as characters data.
Fixes #544.
> Handle escaping < in edge cases where it doesn't start a tag (#544)

- bleach/sanitizer.py
- tests/test_clean.py
Previously, we allowed scheme-less urls if "http" was allowed. This
expands that to also support "https".
Fixes #662
> Support scheme-less urls if "https" is allowed (#662)

- bleach/sanitizer.py
- docs/clean.rst
- setup.cfg
- tests/test_clean.py
This adds a note to the documentation and also adds a warning that gets emitted if css_sanitizer is not set, but "style" is an allowed attribute. This reduces the likelihood of developer error.
Fixes #676.
> Add warning when css_sanitizer is not set, but style is allowed (#676)

- bleach/linkifier.py
- tests/test_linkify.py
This fixes problems where serializing linkify output causes character entities in Characters tokens to be escaped.
Fixes #501
Fixes #670
> Fix linkify with character entities (#501)

- bleach/__init__.py
- bleach/html5lib_shim.py
- bleach/sanitizer.py
This cleans up some API weirdness where `BleachSanitizerFilter` subclasses html5lib's sanitizer filter and sets `allowed_elements` to something entirely different than html5lib's sanitizer filter's `allowed_elements` is. The formers is a list of strings. The latter is a frozenset of `(namespace, element)` tuples.
This fixes that by changing the `BleachSanitizerFilter` code to use `allowed_tags` everywhere. This eliminates the API confusion.
While doing this, I changed `ALLOWED_TAGS` to be a frozenset, changed allowed_tags to take a set of strings rather than a list of strings, and renamed `strip_disallowed_elements` to `strip_disallowed_tags` to be consistent with naming. This is a backwards incompatible change we'll need to mention in `CHANGES` and it means a major version change.
I also …
> Change elements to tags (#649)

- .github/workflows/test.yml
- setup.py
- tox.ini
> Remove support for Python 3.7 (#709)

- bleach/html5lib_shim.py
- tests/test_clean.py
This adds handling for two more cases:
1. something like "<word word". This throws an eof-in-attribute-name parser error.
2. something like "<word word=word". This throws an eof-in-attribute-value-no-quotes error.
Both of these work correctly now.
Fixes #705.
> Handle more cases with < folloed by character data (#705)

- bleach/linkifier.py
- tests/test_linkify.py
> Fix linkify with arrays in querystring (#436)

- Makefile
- requirements-dev.txt
- tests/test_unicode.py
This updates dev dependencies, fixes the lint make rule, and fixes a formatting issue in tests/test_unicode.py.
> Update dev dependencies

- .github/workflows/test.yml
- CHANGES
- setup.py
- tox.ini
> Add support for Python 3.13 (#736)

- bleach/html5lib_shim.py
- tests/test_clean.py
This fixes these two cases:
* "<some thing thing" where "thing" is repeated twice which kicks up a parser error because it thinks it's a duplicated attribute
* "<some thing thing2 " where the space at the end causes a expected-end-of-tag-but-got-eof parser error to pop up
In both of these cases, we want the data to be treated as character data--not a tag.
```python
Python 3.10.14 (main, Aug 14 2024, 05:11:29) [Clang 18.1.8 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bleach
>>> bleach.clean("<test abc abc")
'&lt;test abc abc'
>>> bleach.clean("<test abc ")
'&lt;test abc '
>>> bleach.clean("asd<test abc ")
'asd&lt;test abc '
>>>
```
Fixes #728.
> Fix additional < followed by characters and EOF issues (#728)

- bleach/_vendor/01_html5lib_six.patch
- bleach/_vendor/html5lib/_inputstream.py
- bleach/_vendor/html5lib/_tokenizer.py
- bleach/_vendor/html5lib/_trie/py.py
- bleach/_vendor/html5lib/_utils.py
- bleach/_vendor/html5lib/filters/lint.py
- bleach/_vendor/html5lib/filters/sanitizer.py
- bleach/_vendor/html5lib/html5parser.py
- bleach/_vendor/html5lib/serializer.py
- bleach/_vendor/html5lib/treebuilders/base.py
- bleach/_vendor/html5lib/treebuilders/etree.py
- bleach/_vendor/html5lib/treebuilders/etree_lxml.py
- bleach/_vendor/html5lib/treewalkers/etree.py
- bleach/_vendor/html5lib/treewalkers/etree_lxml.py
- bleach/_vendor/vendor_install.sh
- bleach/six_shim.py
- scripts/vendor_verify.sh
- setup.py
This does some squirrely things in order to drop the six dependency that our vendored html5lib has. The thinking is along these lines:
1. this is the best way to drop the six dependency in the context we have
2. it maintains the rigor we use for vendored libraries
3. it's mostly straightforward and easy to reason about
4. the code changes are minimal--it mostly teaks a small handful of import lines
5. it won't cause problems with other things that are installed alongside bleach and its vendored html5lib
6. html5lib hasn't had a release in a while so this won't meaningfully increase the maintenance burden
The way this works is that vendoring now has two steps:
1. installing html5lib 1.1 into a specific directory with no dependencies
2. applying the `01_html5lib_six.patch`
Fixes #618.
> drop six dependency (#618)
