CONTRIBUTING.rst, README.rst, docs/index.rst
This PR updates the documentation in one place. If we're ok with the wording, then I'll copy it to the other places (README and CONTRIBUTING).
@jezdez, @jvehent : Does this wording and the links work?
=> Add section for security-related bug disclosure

CHANGES, CONTRIBUTORS, README.rst, bleach/__init__.py, docs/changes.rst, docs/clean.rst, docs/conf.py, docs/index.rst, setup.py
This is a bunch of updates to the documentation to:
1. add examples of usage for things that didn't have examples
2. make all examples testable (which uncovered a typo)
3. reduce duplication between README and docs
4. surface CHANGES in the docs (issue #180)
5. add release dates to versions in CHANGES based on tag dates
=> Docs updates

bleach/__init__.py
This picks up the commit from #183 and adds another commit that fixes the issue that was having with Travis.
r?
=> 182 nullhandler

bleach/__init__.py, bleach/tests/test_links.py
=> Children of <pre> tags should not be linkified when skip_pre=True

.travis.yml, setup.cfg
This also makes wheel files be universal (Python 2 & 3).
=> Auto-release to PyPI on tag. Fix #209.

bleach/__init__.py, docs/goals.rst
This clarifies some of the guiding principles behind what bleach is for
and not for so it's clearer to users whether their needs will be met.
=> Clarify docs regarding appropriate use cases and goals

.travis.yml, CHANGES, bleach/__init__.py, bleach/version.py, setup.py, tox.ini
=> Remove support for Python 2.6 and 3.2

README.rst
Capital letters dont seem to be working with badge.fury.io
=> Fixed pypi badge URL

bleach/__init__.py, docs/clean.rst
=> Add cleaner

tests/test_basics.py, tests/test_links.py
* move linkify tests to test_linkify.py
* remove tests that are related to the previous implementation
=> More test cleanup

tests/test_callbacks.py, tests/test_links.py
* adds tests for linkify callbacks
* fix linkify calls to always specify "callbacks" argument name
=> Add tests for linkify callbacks

website/.gitignore, website/README.txt, website/data_to_json.py, website/index.html, website/open_test_page.py, website/server.py
refs: https://github.com/mozilla/bleach/issues/242 https://github.com/mozilla-services/foxsec/issues/133
This probably shouldn't go in as it stands, but I thought I'd document my changes here.
The test page was initially copied from https://cure53.de/purify (dual MPL 2 and Apache licensed which should be compatible) and requires some attribution.
glorious web 1.0 styles:
=> add test website and scripts

docs/goals.rst
Per IRC discussion. Please modify as necessary.
=> docs: Add XSS gadget safe escaping as a non-goal

CHANGES, README.rst
Fixes #303 
@g-k Do the changes to the README look ok to you?
=> Clarify security policy

CODE_OF_CONDUCT.rst, README.rst, docs/dev.rst
=> Add code of conduct blurb, move some docs around

CHANGES
This is clearer regarding the intent of that block.
=> Change "Security issues" to "Security fixes"

tests_website/server.py
Urgh--missed these first time around. :(
=> More Python 3 fixes for tests_websites

CHANGES, bleach/__init__.py, bleach/sanitizer.py, tox.ini
=> Support html5lib-python 1.0.1

CONTRIBUTORS, bleach/sanitizer.py, tests/test_clean.py
Fix for https://github.com/mozilla/bleach/issues/376
=> Fix error when parsing invalid URI

.travis.yml, tox.ini
This makes sure travis and tox are testing Bleach with the same
configurations.
=> Sync travis and tox environments

docs/linkify.rst
=> fixed docs on callback location

docs/clean.rst, docs/linkify.rst
This reworks the doctests to run and pass in Python 3.
Fixes #357
=> Fix doctest failures

tests/test_css.py
This fixes the style tests so they're more explicit and less
composed-on-the-fly which makes them harder to verify.
=> Fix style tests

docs/goals.rst, docs/linkify.rst
refs: #464 and discussion in the associated BMO bug
r? @willkg 
If this looks good, I'll also open an issue for adding examples of how one might handle those threats sanely.
=> docs: add IDN homograph attacks to goals and linkify

bleach/html5lib_shim.py, tests/test_html5lib_shim.py
=> Parser tags nonetype exception

bleach/linkifier.py, docs/linkify.rst
Rebased #486 with a format string escaping comment and docs
=> build email re

tests/test_clean.py
=> Fix simple typo: curren -> current

README.rst
Fix #442 - links to the generated code of conduct
=> Add relative link to code of conduct

CHANGES, bleach/__init__.py, bleach/html5lib_shim.py, tests/test_clean.py
Pull sec-fix in 3.1.1 to master
=> v3.1.0 branch

CHANGES, bleach/__init__.py, bleach/html5lib_shim.py, requirements-dev.txt, tests/test_clean.py
Pulls in changes from the https://bugzilla.mozilla.org/show_bug.cgi?id=1621692 fix
=> 3.1.2 sec release

tests/test_clean.py
=> add tests for void tags #488

CHANGES, CONTRIBUTORS, bleach/__init__.py, bleach/linkifier.py, docs/linkify.rst, tests/test_linkify.py
Carries #509 with tests
https://bleach.readthedocs.io/en/latest/linkify.html says we add nofollow by default
=> add DEFAULT_CALLBACKS to linkifier

bleach/html5lib_shim.py, bleach/sanitizer.py, setup.cfg
fixes: #557 
r? @willkg if you get a minute
=> Fix 557 suppress html5lib sanitizer deprecation warnings

CHANGES, bleach/__init__.py
in docs/ `make html` and `make doctest` pass
=> Update for v3.2.1 release

bleach/html5lib_shim.py, tests/test_linkify.py
fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29581 (private for now)
r? @willkg 
I'll manually check PY2 locally.
=> linkify: fix IndexError in convert_entity

CHANGES, CONTRIBUTORS, bleach/__init__.py
changes from https://github.com/mozilla/bleach/compare/v3.3.0...master
=> Update for v3.3.1 release

bleach/linkifier.py, bleach/sanitizer.py, docs/clean.rst, docs/conf.py, docs/goals.rst, setup.py
=> Fix reference warnings in docs (#660)

.github/workflows/lint.yml, .github/workflows/test.yml, setup.py, tox.ini
=> Add support for Python 3.11 (#675)

CHANGES, bleach/__init__.py, setup.py
While doing this, I fixed some inconsistencies with the CHANGES file.
=> Prep for 6.0.0 release

bleach/linkifier.py, tests/test_linkify.py
=> Fix entities inside a tags in linkification (#704)

.github/workflows/test.yml, CHANGES, Makefile, requirements-dev.txt, setup.py, tox.ini
=> Drop support for Python 3.8 (#737)

setup.py
https://github.com/Kozea/tinycss2/compare/v1.2.1...v1.4.0
The bulk of the changes are project maintenance things like switching linters and supported Python versions.
I think I still want to keep the dependency constraints somewhat pinned down. I get how it causes some issues, but it's safer.
Fixes #732.
=> Update known-good versions of tinycss2 (#732)
